name: huaba.net
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3c646'
    - '#3e3d40'
    - '#89a445'
    - '#565e41'
    - '#708043'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
